# These are supported funding model platforms

github: [VAIBHAVBABELE]
custom: ['upi://pay?pa=8417054915@ptsbi&pn=NitraMitra&am=50&cu=INR&tn=Support%20Nitra%20Mitra', 'upi://pay?pa=8417054915@upi&pn=NitraMitra&am=50&cu=INR&tn=Support%20Nitra%20Mitra']
