name: Auto Comment on Pull Request Creation

on:
  pull_request:
    types: [opened]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.pull_request.user.login;

            const msg = `👋 Hello @${username},\n\nThanks for submitting a pull request! ✨\nPlease ensure:\n- The code follows our [contribution guidelines](https://github.com/VAIBHAVBABELE/vaibhavbabele.github.io/blob/main/CONTRIBUTING.md)\n- You have tested your changes.\n\nWe’ll review and get back to you shortly. 🚀`;

            await github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
