name: Update Contributions Documentation

on:
  pull_request:
    types:
      - closed

jobs:
  update-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch PR details
        id: pr_data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch PR reviews
        id: pr_reviews
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed_files
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set PR info as env
        run: |
          echo "PR_TITLE=$(jq -r '.data.title' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_AUTHOR=$(jq -r '.data.user.login' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_MERGED_BY=$(jq -r '.data.merged_by.login' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_NUMBER=$(jq -r '.data.number' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_DESC=$(jq -r '.data.body' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_LABELS=$(jq -r '.data.labels | map(.name) | join(\", \")' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_TIMESTAMP=$(jq -r '.data.merged_at' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "PR_LAST_COMMIT=$(jq -r '.data.merge_commit_sha' <<< '${{ steps.pr_data.outputs.data }}')" >> $GITHUB_ENV
          echo "CHANGED_FILES=$(jq -r '[.data[].filename] | join(\", \")' <<< '${{ steps.changed_files.outputs.data }}')" >> $GITHUB_ENV
          echo "CHANGED_FILES_COUNT=$(jq -r 'length' <<< '${{ steps.changed_files.outputs.data }}')" >> $GITHUB_ENV
          echo "REVIEWERS=$(jq -r '[.data[].user.login] | join(\", \")' <<< '${{ steps.pr_reviews.outputs.data }}')" >> $GITHUB_ENV

      - name: Append PR info to docs/contributions.md
        run: |
          echo "## PR #${PR_NUMBER} - ${PR_TITLE}" >> docs/contributions.md
          echo "- **Author:** ${PR_AUTHOR}" >> docs/contributions.md
          echo "- **Merged By:** ${PR_MERGED_BY}" >> docs/contributions.md
          echo "- **Description:** ${PR_DESC}" >> docs/contributions.md
          echo "- **Labels:** ${PR_LABELS}" >> docs/contributions.md
          echo "- **Files Changed:** ${CHANGED_FILES_COUNT}" >> docs/contributions.md
          echo "- **Updated Files:** ${CHANGED_FILES}" >> docs/contributions.md
          echo "- **Reviewers:** ${REVIEWERS}" >> docs/contributions.md
          echo "- **Last Commit:** ${PR_LAST_COMMIT}" >> docs/contributions.md
          echo "- **Merged At:** ${PR_TIMESTAMP}" >> docs/contributions.md
          echo "" >> docs/contributions.md

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/contributions.md
          git commit -m "Update contributions documentation for PR #${PR_NUMBER}"
          git push
