name: Auto Comment on Merged Pull Request

on:
  pull_request:
    types: [closed]

jobs:
  merged-pr-comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Thank on Merge
        uses: actions/github-script@v7
        with:
          script: |
            const username = context.payload.pull_request.user.login;

            const msg = `🎉 Congrats @${username}, your pull request has been merged!\nThanks for your contribution 💖\nKeep it up, we appreciate your efforts 🚀`;

            await github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
