name: Thank Contributor

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  thank-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send Thank You Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const prAuthor = context.payload.pull_request.user.login;
              const prNumber = context.payload.pull_request.number;
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `ЁЯОЙ рдзрдиреНрдпрд╡рд╛рдж @${prAuthor} рдЬреА! рдЖрдкрдХрд╛ рдпреЛрдЧрджрд╛рди рд╣рдорд╛рд░реЗ рдкреНрд░реЛрдЬреЗрдХреНрдЯ рдХреЗ рд▓рд┐рдП рдмрд╣реБрдд рдорд╣рддреНрд╡рдкреВрд░реНрдг рд╣реИред ЁЯЩМ`
              });
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `ЁЯЪА рдХреГрдкрдпрд╛ рдЕрдкрдиреЗ рдпреЛрдЧрджрд╛рди рдХреЛ [Discord](https://discord.gg/cYkT2F3v) рдкрд░ рд╕рд╛рдЭрд╛ рдХрд░реЗрдВ рддрд╛рдХрд┐ рд╣рдо рдЗрд╕реЗ рдФрд░ рднреА рдмреЗрд╣рддрд░ рдмрдирд╛ рд╕рдХреЗрдВред
                рдХреГрдкрдпрд╛ рдЕрдЧрд▓реА рдмрд╛рд░ рдпреЛрдЧрджрд╛рди рджреЗрдиреЗ рд╕реЗ рдкрд╣рд▓реЗ рдЕрдкрдиреА Local Repository рдХреЛ рдЕрдкрдбреЗрдЯ (fetch/pull) рдХрд░рдирд╛ рди рднреВрд▓реЗрдВ рддрд╛рдХрд┐ рдХреЛрдИ conflict рди рд╣реЛред ЁЯШК`
              });