name: PR Preview Link

on: [pull_request]

jobs:
  comment-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Comment with Preview
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔗 Preview your changes here: https://${context.repo.owner}.github.io/${context.repo.repo}`
            })
