name: Thank Contributor

on:
  pull_request:
    types: [closed]

jobs:
  thanks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Thank you @${{ github.actor }} for your contribution!
              ✅ Your PR is now merged.  
              Don’t forget to star the repo. 
              💬 Join us on [LinkedIn](https://www.linkedin.com/in/vaibhavbabele) 
              📌 Feel free to open more issues!
              — Owner: @vaibhavbabele 🙏`
            })
